import type { AIConfig } from '@botforge/shared'

/**
 * Renders src/services/ai.service.ts for the generated bot.
 *
 * Provider-agnostic AI service. Supports OpenAI and Gemini.
 * The generated code picks the right SDK based on config.
 *
 * Modes control the system prompt behavior:
 *   - faq:        answer from knowledge base, refuse unknowns
 *   - sales:      recommend products, push toward purchase
 *   - support:    diagnose issues, escalate when stuck
 *   - consultant: free-form expert conversation
 */
export function renderAIServiceTs(config: AIConfig): string {
  const provider = config.provider
  const mode = config.mode
  const systemPrompt = JSON.stringify(config.systemPrompt || buildDefaultSystemPrompt(mode))
  const fallbackMsg = JSON.stringify(config.fallbackMessage)
  const temperature = config.temperature
  const maxTokens = config.maxTokens
  const fallbackToHuman = config.fallbackToHuman
  const model = JSON.stringify(config.model || defaultModel(provider))

  const kbEntries = config.knowledgeBase ?? []
  const hasKB = kbEntries.length > 0
  const kbLiteral = JSON.stringify(kbEntries, null, 2)

  return `// Auto-generated by BotForge — do not edit
${provider === 'openai'
    ? "import OpenAI from 'openai'"
    : "import { GoogleGenerativeAI } from '@google/generative-ai'"
}

// ── Config ───────────────────────────────────────────────────────────────────

const API_KEY = process.env.AI_API_KEY
if (!API_KEY) console.warn('AI_API_KEY not set — AI responses will fail')

const MODEL = ${model}
const TEMPERATURE = ${temperature}
const MAX_TOKENS = ${maxTokens}
const FALLBACK_MESSAGE = ${fallbackMsg}
const FALLBACK_TO_HUMAN = ${fallbackToHuman}
const SYSTEM_PROMPT = ${systemPrompt}

${hasKB ? `
// ── Knowledge base ───────────────────────────────────────────────────────────

interface KBEntry { question: string; answer: string }
const KNOWLEDGE_BASE: KBEntry[] = ${kbLiteral}

function buildKBContext(): string {
  if (KNOWLEDGE_BASE.length === 0) return ''
  const lines = KNOWLEDGE_BASE.map(
    (e, i) => \`Q\${i + 1}: \${e.question}\\nA\${i + 1}: \${e.answer}\`
  )
  return '\\n\\nBilim bazasi:\\n' + lines.join('\\n\\n')
}
` : ''}

// ── Conversation history ─────────────────────────────────────────────────────

interface Message { role: 'user' | 'assistant'; content: string }
const histories = new Map<number, Message[]>()
const MAX_HISTORY = 10

function getHistory(userId: number): Message[] {
  if (!histories.has(userId)) histories.set(userId, [])
  return histories.get(userId)!
}

export function clearHistory(userId: number): void {
  histories.delete(userId)
}

function addToHistory(userId: number, role: 'user' | 'assistant', content: string): void {
  const hist = getHistory(userId)
  hist.push({ role, content })
  if (hist.length > MAX_HISTORY * 2) hist.splice(0, 2)
}

// ── AI response ──────────────────────────────────────────────────────────────

export interface AIResponse {
  text: string
  fallback: boolean    // true if AI failed and we returned fallback message
  escalate: boolean    // true if AI recommends human handoff
}

export async function getAIResponse(userId: number, userMessage: string): Promise<AIResponse> {
  if (!API_KEY) {
    return { text: FALLBACK_MESSAGE, fallback: true, escalate: FALLBACK_TO_HUMAN }
  }

  addToHistory(userId, 'user', userMessage)

  try {
    const fullSystem = SYSTEM_PROMPT${hasKB ? " + buildKBContext()" : ''}
    const reply = await callProvider(fullSystem, getHistory(userId))

    // Check for escalation signals
    const lower = reply.toLowerCase()
    const escalate = FALLBACK_TO_HUMAN && (
      lower.includes('[escalate]')
      || lower.includes('[operator]')
      || lower.includes('[human]')
    )

    const cleanReply = reply
      .replace(/\\[escalate\\]/gi, '')
      .replace(/\\[operator\\]/gi, '')
      .replace(/\\[human\\]/gi, '')
      .trim()

    addToHistory(userId, 'assistant', cleanReply)

    return { text: cleanReply, fallback: false, escalate }
  } catch (err) {
    console.error('AI request failed:', err instanceof Error ? err.message : err)
    return { text: FALLBACK_MESSAGE, fallback: true, escalate: FALLBACK_TO_HUMAN }
  }
}

// ── Provider implementations ─────────────────────────────────────────────────

${provider === 'openai' ? renderOpenAIProvider() : renderGeminiProvider()}
`
}

function renderOpenAIProvider(): string {
  return `
async function callProvider(systemPrompt: string, history: Message[]): Promise<string> {
  const client = new OpenAI({ apiKey: API_KEY })

  const messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }> = [
    { role: 'system', content: systemPrompt },
    ...history.map(m => ({ role: m.role, content: m.content })),
  ]

  const response = await client.chat.completions.create({
    model: MODEL,
    messages,
    temperature: TEMPERATURE,
    max_tokens: MAX_TOKENS,
  })

  return response.choices[0]?.message?.content?.trim() || FALLBACK_MESSAGE
}
`
}

function renderGeminiProvider(): string {
  return `
async function callProvider(systemPrompt: string, history: Message[]): Promise<string> {
  const genAI = new GoogleGenerativeAI(API_KEY!)
  const model = genAI.getGenerativeModel({
    model: MODEL,
    systemInstruction: systemPrompt,
  })

  const chat = model.startChat({
    history: history.slice(0, -1).map(m => ({
      role: m.role === 'user' ? 'user' : 'model',
      parts: [{ text: m.content }],
    })),
    generationConfig: {
      temperature: TEMPERATURE,
      maxOutputTokens: MAX_TOKENS,
    },
  })

  const lastMessage = history[history.length - 1]?.content || ''
  const result = await chat.sendMessage(lastMessage)
  return result.response.text()?.trim() || FALLBACK_MESSAGE
}
`
}

// ── Default system prompts per mode ──────────────────────────────────────────

function buildDefaultSystemPrompt(mode: string): string {
  switch (mode) {
    case 'faq':
      return `Sen FAQ botisan. Foydalanuvchilarning savollariga bilim bazasi asosida javob ber.
Agar bilim bazasida javob topmasang, "Bu savolga hozircha javob bera olmayman" deb ayt.
Qisqa va aniq javob ber. Hech qachon o'ylab topma.`

    case 'sales':
      return `Sen sotuv yordamchisisan. Mijozlarga mahsulot tanlashda yordam ber.
Xushmuomala va foydali bo'l. Mahsulotlar haqida bilim bazasidan foydalanib javob ber.
Agar mijoz buyurtma bermoqchi bo'lsa, /start buyrug'ini bosishini ayt.`

    case 'support':
      return `Sen texnik yordam botisan. Muammolarni tushunishga va hal qilishga yordam ber.
Agar muammoni hal qila olmasang, [ESCALATE] yozib operatorga yo'naltir.
Sabr bilan va tushunarli tilda javob ber.`

    case 'consultant':
      return `Sen professional maslahatchi botisan. Ekspert sifatida savollarga javob ber.
Aniq va foydali maslahat ber. Bilmagan narsang bo'lsa, ochiq ayt.`

    default:
      return 'Sen yordamchi botisan. Savollarga qisqa va aniq javob ber.'
  }
}

function defaultModel(provider: string): string {
  return provider === 'openai' ? 'gpt-4o-mini' : 'gemini-2.0-flash'
}
