import type { MenuItemConfig } from './render-router'

/**
 * Renders src/flows/menu.flow.ts for the generated bot.
 *
 * Displays an inline keyboard menu. Each button can:
 *   - 'form'  → transition to the form flow
 *   - 'url'   → show a link
 *   - 'text'  → reply with static text
 *
 * Menu items come from the user's BotForge config at generation time.
 */
export function renderMenuFlowTs(items: MenuItemConfig[]): string {
  const itemsLiteral = JSON.stringify(items, null, 2)

  return `// Auto-generated by BotForge — do not edit
import { Markup } from 'telegraf'
import type { Context } from 'telegraf'
import { setFlow, type Session } from '../utils/session'
import { startForm } from './form.flow'

// ── Menu config (baked from BotForge) ────────────────────────────────────────

interface MenuItem {
  label: string
  action: 'form' | 'url' | 'text'
  value: string
}

const MENU_ITEMS: MenuItem[] = ${itemsLiteral}

// ── Show menu ────────────────────────────────────────────────────────────────

export async function show(ctx: Context, session: Session): Promise<void> {
  setFlow(session, 'menu')

  const buttons = MENU_ITEMS.map((item, i) => {
    if (item.action === 'url') {
      return [Markup.button.url(item.label, item.value)]
    }
    return [Markup.button.callback(item.label, 'menu_' + i)]
  })

  await ctx.reply('Tanlang:', Markup.inlineKeyboard(buttons))
}

// ── Handle menu selection ────────────────────────────────────────────────────

export async function handleSelection(
  ctx: any,
  session: Session,
  callbackData: string,
  _bot: any,
): Promise<void> {
  const idx = parseInt(callbackData.replace('menu_', ''), 10)
  const item = MENU_ITEMS[idx]
  if (!item) {
    await ctx.answerCbQuery('Topilmadi')
    return
  }

  await ctx.answerCbQuery()

  switch (item.action) {
    case 'form':
      await ctx.editMessageText(item.label + ' ✓')
      setFlow(session, 'form')
      await startForm(ctx)
      break

    case 'text':
      await ctx.editMessageText(item.value)
      // Stay in menu — user can /menu again
      setFlow(session, 'idle')
      break

    case 'url':
      // URL buttons are handled by Telegram directly, not callbacks
      break
  }
}
`
}
