/**
 * Renders src/utils/validation.ts for the generated bot.
 *
 * This file lives INSIDE the generated bot at runtime.
 * It provides input validation functions the form flow calls.
 */
export function renderValidationTs(): string {
  return `// Auto-generated by BotForge — do not edit

export type FieldType = 'text' | 'email' | 'phone' | 'contact_share' | 'number' | 'select' | 'date'

export interface ValidationResult {
  valid: boolean
  error?: string
}

const EMAIL_RE = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/
const PHONE_RE = /^\\+?[0-9\\s\\-()]{7,20}$/
const DATE_RE = /^\\d{4}-\\d{2}-\\d{2}$|^\\d{2}[.\\/\\-]\\d{2}[.\\/\\-]\\d{4}$/

export function validateField(
  value: string,
  type: FieldType,
  required: boolean,
): ValidationResult {
  const trimmed = value.trim()

  if (!trimmed) {
    return required
      ? { valid: false, error: 'Bu maydon to\\'ldirish shart' }
      : { valid: true }
  }

  switch (type) {
    case 'email':
      return EMAIL_RE.test(trimmed)
        ? { valid: true }
        : { valid: false, error: 'Email formati noto\\'g\\'ri (masalan: user@mail.com)' }

    case 'phone':
      return PHONE_RE.test(trimmed)
        ? { valid: true }
        : { valid: false, error: 'Telefon raqam formati noto\\'g\\'ri' }

    case 'number': {
      const num = Number(trimmed)
      return !isNaN(num) && num > 0
        ? { valid: true }
        : { valid: false, error: 'Son kiriting' }
    }

    case 'date':
      return DATE_RE.test(trimmed)
        ? { valid: true }
        : { valid: false, error: 'Sana formati noto\\'g\\'ri (masalan: 25.12.2025)' }

    case 'text':
    case 'select':
    case 'contact_share':
    default:
      return { valid: true }
  }
}
`
}
