/**
 * Renders src/utils/session.ts for the generated bot.
 *
 * Tracks: which flow is active, form field progress, collected data,
 * and template-specific extras (cart, booking selection, etc.).
 */
export function renderSessionTs(): string {
  return `// Auto-generated by BotForge — do not edit

// ── Flow names ───────────────────────────────────────────────────────────────
// Each flow registers itself. The router checks session.activeFlow to decide
// which flow handles incoming messages.

export type FlowName = 'idle' | 'form' | 'menu' | 'admin' | string

// ── Field definition (used by form flow) ─────────────────────────────────────

export interface FieldDef {
  key: string
  label: string
  type: 'text' | 'email' | 'phone' | 'contact_share' | 'number' | 'select' | 'date'
  required: boolean
  prompt: string
  errorMessage?: string
  options?: string[]
}

// ── Session ──────────────────────────────────────────────────────────────────

export interface Session {
  /** Which flow currently owns this user's conversation */
  activeFlow: FlowName
  /** Index into the form FIELDS array (only used by form flow) */
  currentFieldIndex: number
  /** Collected form values keyed by field key */
  data: Record<string, string>
  /** True when form flow has collected all fields */
  completed: boolean
  /** Template-specific state (cart items, booking selection, ticket, etc.) */
  extra: Record<string, unknown>
}

const sessions = new Map<number, Session>()

export function getSession(userId: number): Session {
  if (!sessions.has(userId)) {
    sessions.set(userId, createFreshSession())
  }
  return sessions.get(userId)!
}

export function resetSession(userId: number): Session {
  const fresh = createFreshSession()
  sessions.set(userId, fresh)
  return fresh
}

function createFreshSession(): Session {
  return {
    activeFlow: 'idle',
    currentFieldIndex: 0,
    data: {},
    completed: false,
    extra: {},
  }
}

/**
 * Switch the active flow. Resets form progress if switching to 'form'.
 */
export function setFlow(session: Session, flow: FlowName): void {
  session.activeFlow = flow
  if (flow === 'form') {
    session.currentFieldIndex = 0
    session.data = {}
    session.completed = false
  }
}

// ── Form field helpers ───────────────────────────────────────────────────────

export function advanceField(session: Session, fields: FieldDef[]): number {
  session.currentFieldIndex++
  if (session.currentFieldIndex >= fields.length) {
    session.completed = true
    return -1
  }
  return session.currentFieldIndex
}

export function currentField(session: Session, fields: FieldDef[]): FieldDef | null {
  if (session.completed || session.currentFieldIndex >= fields.length) return null
  return fields[session.currentFieldIndex]
}

export function formatSubmission(session: Session, fields: FieldDef[]): string {
  return fields
    .filter(f => session.data[f.key] !== undefined && session.data[f.key] !== '')
    .map(f => \`\${f.label}: \${session.data[f.key]}\`)
    .join('\\n')
}
`
}
