import type { StatusStep } from '@botforge/shared'

/**
 * Renders src/flows/admin.flow.ts for the generated bot.
 *
 * Three responsibilities:
 *   1. Submission store — records form completions with status tracking
 *   2. Status workflow  — admin updates status via inline buttons, user gets notified
 *   3. Admin commands   — /stats, /export
 *
 * Status flow (example):
 *   Form done → submission created (status: steps[0]) → admin gets message with buttons
 *   → admin taps "Tasdiqlash" → status moves to steps[1] → user gets notification
 *   → admin taps "Yo'lda" → status moves to steps[2] → user gets notification
 *   → ...
 */
export function renderAdminFlowTs(opts: {
  statsEnabled: boolean
  exportEnabled: boolean
  statusSteps: StatusStep[]
}): string {
  const hasWorkflow = opts.statusSteps.length > 0
  const stepsLiteral = JSON.stringify(opts.statusSteps, null, 2)

  return `// Auto-generated by BotForge — do not edit
import { Markup } from 'telegraf'
import type { Context } from 'telegraf'
import { FIELDS } from './form.flow'
import { formatSubmission, type Session } from '../utils/session'

const OWNER_CHAT_ID = process.env.OWNER_CHAT_ID

// ── Status workflow config ───────────────────────────────────────────────────

interface StatusStep {
  key: string
  label: string
  notifyAdmin: boolean
  notifyUser: boolean
  userMessage?: string
}

const STATUS_STEPS: StatusStep[] = ${stepsLiteral}

// ── Submission store ─────────────────────────────────────────────────────────

interface Submission {
  id: number
  userId: number
  displayName: string
  username: string
  data: Record<string, string>
  statusKey: string
  statusLabel: string
  adminMessageId?: number
  createdAt: Date
  updatedAt: Date
}

const submissions: Submission[] = []
let counter = 0

// ── Record a new submission ──────────────────────────────────────────────────

export function recordSubmission(ctx: Context, data: Record<string, string>): Submission {
  const from = ctx.from!
  counter++

  const initialStatus = STATUS_STEPS.length > 0
    ? STATUS_STEPS[0]
    : { key: 'new', label: 'Yangi' }

  const submission: Submission = {
    id: counter,
    userId: from.id,
    displayName: [from.first_name, from.last_name].filter(Boolean).join(' '),
    username: from.username || '',
    data: { ...data },
    statusKey: initialStatus.key,
    statusLabel: initialStatus.label,
    createdAt: new Date(),
    updatedAt: new Date(),
  }

  submissions.push(submission)
  return submission
}

export function getSubmission(id: number): Submission | undefined {
  return submissions.find(s => s.id === id)
}

export function getSubmissionCount(): number {
  return submissions.length
}

// ── Format submission for admin ──────────────────────────────────────────────

function formatForAdmin(sub: Submission): string {
  const lines: string[] = [
    \`📋 #\${sub.id} — \${sub.statusLabel}\`,
    '',
    \`👤 \${sub.displayName}\${sub.username ? ' (@' + sub.username + ')' : ''}\`,
    \`🆔 \${sub.userId}\`,
    '',
  ]

  for (const field of FIELDS) {
    const val = sub.data[field.key]
    if (val !== undefined && val !== '') {
      lines.push(\`\${field.label}: \${val}\`)
    }
  }

  lines.push('')
  lines.push(\`⏰ \${sub.createdAt.toLocaleString('uz')}\`)

  return lines.join('\\n')
}

${hasWorkflow ? `
// ── Status action buttons ────────────────────────────────────────────────────

function statusButtons(submissionId: number, currentKey: string): any {
  const currentIdx = STATUS_STEPS.findIndex(s => s.key === currentKey)
  const buttons: any[][] = []

  // Show next possible statuses (current + 1, current + 2, and cancel)
  for (let i = currentIdx + 1; i < STATUS_STEPS.length; i++) {
    const step = STATUS_STEPS[i]
    buttons.push([
      Markup.button.callback(
        step.label + (step.key === 'cancelled' ? ' ❌' : ' →'),
        'status_' + submissionId + '_' + step.key,
      )
    ])
  }

  return Markup.inlineKeyboard(buttons)
}
` : ''}

// ── Send admin notification with action buttons ──────────────────────────────

export async function notifyAdminWithActions(
  bot: any,
  ctx: Context,
  session: Session,
): Promise<void> {
  if (!OWNER_CHAT_ID) return

  // Record submission
  const sub = recordSubmission(ctx, session.data)
  const text = formatForAdmin(sub)

${hasWorkflow ? `
  // Send with status buttons
  try {
    const sent = await bot.telegram.sendMessage(OWNER_CHAT_ID, text, statusButtons(sub.id, sub.statusKey))
    sub.adminMessageId = sent.message_id
  } catch (err) {
    console.error('Failed to notify admin:', err)
  }
` : `
  // Send plain text (no workflow)
  try {
    await bot.telegram.sendMessage(OWNER_CHAT_ID, text)
  } catch (err) {
    console.error('Failed to notify admin:', err)
  }
`}
}

${hasWorkflow ? `
// ── Handle status update callback ────────────────────────────────────────────

export async function handleStatusUpdate(
  ctx: any,
  bot: any,
  callbackData: string,
): Promise<void> {
  // Format: status_{submissionId}_{statusKey}
  const parts = callbackData.split('_')
  if (parts.length < 3) return

  const subId = parseInt(parts[1])
  const newStatusKey = parts.slice(2).join('_')
  const sub = getSubmission(subId)

  if (!sub) {
    await ctx.answerCbQuery('Murojaat topilmadi')
    return
  }

  const newStep = STATUS_STEPS.find(s => s.key === newStatusKey)
  if (!newStep) {
    await ctx.answerCbQuery('Noma\\'lum holat')
    return
  }

  // Update status
  const oldLabel = sub.statusLabel
  sub.statusKey = newStep.key
  sub.statusLabel = newStep.label
  sub.updatedAt = new Date()

  await ctx.answerCbQuery(newStep.label + ' ✓')

  // Update admin message with new status + new buttons
  const updatedText = formatForAdmin(sub)
  const isTerminal = STATUS_STEPS.indexOf(newStep) === STATUS_STEPS.length - 1
    || newStep.key === 'cancelled'
    || newStep.key === 'completed'
    || newStep.key === 'delivered'

  try {
    if (isTerminal) {
      // No more buttons — final state
      await ctx.editMessageText(updatedText + '\\n\\n✅ Yakunlandi')
    } else {
      await ctx.editMessageText(updatedText, statusButtons(sub.id, sub.statusKey))
    }
  } catch (err) {
    // Message might be too old to edit
    console.error('Failed to update admin message:', err)
  }

  // Notify user about status change
  if (newStep.notifyUser && newStep.userMessage) {
    try {
      const userMsg = newStep.userMessage
        .replace('{id}', String(sub.id))
        .replace('{status}', newStep.label)
      await bot.telegram.sendMessage(sub.userId, userMsg)
    } catch (err) {
      console.error(\`Failed to notify user \${sub.userId}:\`, err)
    }
  }
}
` : ''}

// ── Admin commands ───────────────────────────────────────────────────────────

export async function handleCommand(
  ctx: Context,
  command: string,
  _bot: any,
): Promise<void> {
  const chatId = ctx.chat?.id?.toString()
  if (chatId !== OWNER_CHAT_ID) {
    await ctx.reply('Bu buyruq faqat admin uchun.')
    return
  }

  switch (command) {
${opts.statsEnabled ? `    case '/stats':
      await handleStats(ctx)
      break
` : ''}
${opts.exportEnabled ? `    case '/export':
      await handleExport(ctx)
      break
` : ''}
    default:
      await ctx.reply('Noma\\'lum buyruq')
  }
}

${opts.statsEnabled ? `
async function handleStats(ctx: Context): Promise<void> {
  const total = submissions.length
  const today = submissions.filter(s => {
    const d = s.createdAt; const now = new Date()
    return d.getFullYear() === now.getFullYear()
      && d.getMonth() === now.getMonth()
      && d.getDate() === now.getDate()
  }).length

  const uniqueUsers = new Set(submissions.map(s => s.userId)).size

  const lines = [
    '📊 Statistika',
    '',
    'Jami: ' + total + ' ta murojaat',
    'Bugun: ' + today + ' ta',
    'Unikal foydalanuvchilar: ' + uniqueUsers,
  ]

${hasWorkflow ? `
  // Status breakdown
  const byStatus: Record<string, number> = {}
  for (const sub of submissions) {
    byStatus[sub.statusLabel] = (byStatus[sub.statusLabel] || 0) + 1
  }
  if (Object.keys(byStatus).length > 0) {
    lines.push('')
    lines.push('Holat bo\\'yicha:')
    for (const [label, count] of Object.entries(byStatus)) {
      lines.push('  ' + label + ': ' + count)
    }
  }
` : ''}

  if (total > 0) {
    lines.push('')
    lines.push('Oxirgi 5 ta:')
    const recent = submissions.slice(-5).reverse()
    for (const s of recent) {
      const time = s.createdAt.toLocaleTimeString('uz', { hour: '2-digit', minute: '2-digit' })
      lines.push('  #' + s.id + ' ' + time + ' — ' + s.displayName + ' [' + s.statusLabel + ']')
    }
  }

  await ctx.reply(lines.join('\\n'))
}
` : ''}

${opts.exportEnabled ? `
async function handleExport(ctx: Context): Promise<void> {
  if (submissions.length === 0) {
    await ctx.reply('Hozircha murojaatlar yo\\'q.')
    return
  }

  const header = ['#', 'Holat', ...FIELDS.map(f => f.label), 'Vaqt'].join(' | ')
  const rows = submissions.map(s => {
    const time = s.createdAt.toLocaleString('uz', { hour: '2-digit', minute: '2-digit', day: '2-digit', month: '2-digit' })
    return [s.id, s.statusLabel, ...FIELDS.map(f => s.data[f.key] || '-'), time].join(' | ')
  })

  const text = header + '\\n' + '-'.repeat(Math.min(header.length, 60)) + '\\n' + rows.join('\\n')

  if (text.length > 4000) {
    const chunks: string[] = []
    let current = header + '\\n' + '-'.repeat(Math.min(header.length, 60)) + '\\n'
    for (const row of rows) {
      if (current.length + row.length + 1 > 4000) { chunks.push(current); current = '' }
      current += row + '\\n'
    }
    if (current) chunks.push(current)
    for (const chunk of chunks) await ctx.reply(chunk)
  } else {
    await ctx.reply(text)
  }
}
` : ''}
`
}
