import type { CollectField } from '@botforge/shared'

/**
 * Renders src/flows/form.flow.ts for the generated bot.
 *
 * Config-driven form engine. Reads FIELDS[] at runtime, walks the user
 * through each one with validation. Exports handlers that the router calls.
 *
 * Does NOT handle /start or commands — the router does that.
 * This flow only owns the "form" activeFlow state.
 */
export function renderFormFlowTs(
  fields: CollectField[],
  successMessage: string,
  opts: { hasAdmin: boolean; hasStatusWorkflow: boolean },
): string {
  const fieldsLiteral = JSON.stringify(fields, null, 2)
  const successLiteral = JSON.stringify(successMessage)

  return `// Auto-generated by BotForge — do not edit
import { Markup } from 'telegraf'
import type { Context } from 'telegraf'
import {
  getSession, setFlow, advanceField, currentField, formatSubmission,
  type FieldDef, type Session,
} from '../utils/session'
import { validateField } from '../utils/validation'
${opts.hasStatusWorkflow
    ? "import { notifyAdminWithActions } from './admin.flow'"
    : "import { notifyAdmin } from '../services/notify'"
}
${opts.hasAdmin && !opts.hasStatusWorkflow ? "import { recordSubmission } from './admin.flow'" : ''}

// ── Field config (baked from BotForge config) ────────────────────────────────

export const FIELDS: FieldDef[] = ${fieldsLiteral}
export const SUCCESS_MESSAGE = ${successLiteral}

// ── Start form ───────────────────────────────────────────────────────────────

export async function startForm(ctx: Context): Promise<void> {
  const session = getSession(ctx.from!.id)
  setFlow(session, 'form')
  await promptCurrentField(ctx, session)
}

// ── Prompt the current field ─────────────────────────────────────────────────

export async function promptCurrentField(ctx: Context, session: Session): Promise<void> {
  const field = currentField(session, FIELDS)
  if (!field) return

  if (field.type === 'contact_share') {
    await ctx.reply(
      field.prompt,
      Markup.keyboard([
        [Markup.button.contactRequest('📱 ' + field.label)],
      ]).resize().oneTime(),
    )
    return
  }

  if (field.type === 'select' && field.options?.length) {
    const buttons = field.options.map((opt: string) =>
      [Markup.button.callback(opt, 'select_' + field.key + '_' + opt)]
    )
    await ctx.reply(field.prompt, Markup.inlineKeyboard(buttons))
    return
  }

  const hint = field.required ? '' : ' (ixtiyoriy — /skip bosing)'
  await ctx.reply(field.prompt + hint)
}

// ── Handle text answer ───────────────────────────────────────────────────────

export async function handleTextAnswer(
  ctx: Context & { message: { text: string } },
  onComplete: (ctx: Context, session: Session) => Promise<void>,
): Promise<void> {
  const userId = ctx.from!.id
  const session = getSession(userId)
  const field = currentField(session, FIELDS)

  if (!field || session.completed) {
    await ctx.reply('/start bosing')
    return
  }

  const text = ctx.message.text.trim()

  if (text === '/skip' && !field.required) {
    session.data[field.key] = ''
    const next = advanceField(session, FIELDS)
    if (next === -1) {
      await ctx.reply(SUCCESS_MESSAGE, Markup.removeKeyboard())
      await onComplete(ctx, session)
    } else {
      await promptCurrentField(ctx, session)
    }
    return
  }

  const result = validateField(text, field.type, field.required)
  if (!result.valid) {
    const errMsg = field.errorMessage || result.error || 'Noto\\'g\\'ri format'
    await ctx.reply('❌ ' + errMsg + '\\n\\nQayta kiriting:')
    return
  }

  session.data[field.key] = text
  const next = advanceField(session, FIELDS)
  if (next === -1) {
    await ctx.reply(SUCCESS_MESSAGE, Markup.removeKeyboard())
    await onComplete(ctx, session)
  } else {
    await promptCurrentField(ctx, session)
  }
}

// ── Handle contact share ─────────────────────────────────────────────────────

export async function handleContactAnswer(
  ctx: Context & { message: { contact: { phone_number: string } } },
  onComplete: (ctx: Context, session: Session) => Promise<void>,
): Promise<void> {
  const userId = ctx.from!.id
  const session = getSession(userId)
  const field = currentField(session, FIELDS)

  if (!field || field.type !== 'contact_share') return

  session.data[field.key] = ctx.message.contact.phone_number
  const next = advanceField(session, FIELDS)
  if (next === -1) {
    await ctx.reply(SUCCESS_MESSAGE, Markup.removeKeyboard())
    await onComplete(ctx, session)
  } else {
    await promptCurrentField(ctx, session)
  }
}

// ── Handle select callback ───────────────────────────────────────────────────

export function buildSelectHandler(
  onComplete: (ctx: Context, session: Session) => Promise<void>,
) {
  return async (ctx: any) => {
    const data: string = ctx.callbackQuery?.data ?? ''
    const userId = ctx.from!.id
    const session = getSession(userId)
    const field = currentField(session, FIELDS)

    if (!field || field.type !== 'select') return
    const prefix = 'select_' + field.key + '_'
    if (!data.startsWith(prefix)) return

    const selected = data.slice(prefix.length)
    session.data[field.key] = selected
    await ctx.answerCbQuery(selected + ' ✓')

    const next = advanceField(session, FIELDS)
    if (next === -1) {
      await ctx.editMessageText(SUCCESS_MESSAGE)
      await onComplete(ctx, session)
    } else {
      await ctx.editMessageText(field.label + ': ' + selected)
      await promptCurrentField(ctx, session)
    }
  }
}

// ── Form completion handler (called by router) ──────────────────────────────

export async function onFormComplete(ctx: Context, session: Session, bot: any): Promise<void> {
${opts.hasStatusWorkflow
    ? '  await notifyAdminWithActions(bot, ctx, session)'
    : `${opts.hasAdmin ? '  recordSubmission(ctx, session.data)\n' : ''}  await notifyAdmin(bot, ctx, session)`
}
}
`
}
