/**
 * Renders src/router.ts for the generated bot.
 *
 * Central message dispatcher. Routes:
 *   - Global commands (/start, /menu, /help, /stats, /export)
 *   - Active flow text/contact handling
 *   - Callback queries (menu_, select_, status_)
 *   - AI fallback for idle messages (when AI is enabled)
 */

export interface MenuItemConfig {
  label: string
  action: 'form' | 'url' | 'text'
  value: string
}

export function renderRouterTs(opts: {
  hasMenu: boolean
  hasAdmin: boolean
  hasStatusWorkflow: boolean
  hasAI: boolean
}): string {
  return `// Auto-generated by BotForge — do not edit
import type { Context } from 'telegraf'
import { getSession, setFlow, type Session } from './utils/session'

import * as startFlow from './flows/start.flow'
import * as formFlow from './flows/form.flow'
${opts.hasMenu ? "import * as menuFlow from './flows/menu.flow'" : ''}
${opts.hasAdmin ? "import * as adminFlow from './flows/admin.flow'" : ''}
${opts.hasAI ? "import * as aiFlow from './flows/ai.flow'" : ''}

// ── Text router ──────────────────────────────────────────────────────────────

export async function handleText(
  ctx: Context & { message: { text: string } },
  bot: any,
): Promise<void> {
  const text = ctx.message.text.trim()
  const userId = ctx.from!.id
  const session = getSession(userId)

  // Global commands
  if (text === '/start') {
    await startFlow.handle(ctx, session, bot)
    return
  }
${opts.hasMenu ? `
  if (text === '/menu') {
    setFlow(session, 'menu')
    await menuFlow.show(ctx, session)
    return
  }
` : ''}
${opts.hasAdmin ? `
  if (text === '/stats' || text === '/export') {
    await adminFlow.handleCommand(ctx, text, bot)
    return
  }
` : ''}
${opts.hasAI ? `
  if (text === '/ai') {
    setFlow(session, 'ai')
    await ctx.reply('AI yordamchi rejimi. Savolingizni yozing.\\n/start — chiqish')
    return
  }
` : ''}
  if (text === '/help') {
    const lines = ['/start — Qayta boshlash']
${opts.hasMenu ? "    lines.push('/menu — Menyu')" : ''}
${opts.hasAI ? "    lines.push('/ai — AI yordamchi')" : ''}
${opts.hasAdmin ? "    lines.push('/stats — Statistika')" : ''}
${opts.hasAdmin ? "    lines.push('/export — Eksport')" : ''}
    await ctx.reply(lines.join('\\n'))
    return
  }

  // Skip commands when in a flow
  if (text.startsWith('/')) return

  // Active flow handling
  switch (session.activeFlow) {
    case 'form':
      await formFlow.handleTextAnswer(ctx, async (_ctx, sess) => {
        setFlow(sess, 'idle')
        await formFlow.onFormComplete(_ctx, sess, bot)
      })
      break
${opts.hasMenu ? `
    case 'menu':
      await menuFlow.show(ctx, session)
      break
` : ''}
${opts.hasAI ? `
    case 'ai':
      await aiFlow.handleMessage(ctx, bot)
      break
` : ''}
    case 'idle':
    default:
${opts.hasAI
    // AI-enabled bots: idle messages go to AI
    ? "      await aiFlow.handleMessage(ctx, bot)"
    : opts.hasMenu
      ? "      await menuFlow.show(ctx, session)"
      : "      await ctx.reply('/start bosing')"
}
      break
  }
}

// ── Contact router ───────────────────────────────────────────────────────────

export async function handleContact(
  ctx: Context & { message: { contact: { phone_number: string } } },
  bot: any,
): Promise<void> {
  const session = getSession(ctx.from!.id)

  if (session.activeFlow === 'form') {
    await formFlow.handleContactAnswer(ctx, async (_ctx, sess) => {
      setFlow(sess, 'idle')
      await formFlow.onFormComplete(_ctx, sess, bot)
    })
  }
}

// ── Callback query router ────────────────────────────────────────────────────

export async function handleCallback(
  ctx: any,
  bot: any,
): Promise<void> {
  const data: string = ctx.callbackQuery?.data ?? ''
  const session = getSession(ctx.from!.id)

${opts.hasMenu ? `
  if (data.startsWith('menu_')) {
    await menuFlow.handleSelection(ctx, session, data, bot)
    return
  }
` : ''}

${opts.hasStatusWorkflow ? `
  if (data.startsWith('status_')) {
    await adminFlow.handleStatusUpdate(ctx, bot, data)
    return
  }
` : ''}

  // Form select fields
  if (data.startsWith('select_') && session.activeFlow === 'form') {
    const handler = formFlow.buildSelectHandler(async (_ctx: any, sess: Session) => {
      setFlow(sess, 'idle')
      await formFlow.onFormComplete(_ctx, sess, bot)
    })
    await handler(ctx)
    return
  }
}
`
}
