/**
 * Renders src/flows/ai.flow.ts for the generated bot.
 *
 * Handles free-text conversation with the AI service.
 * When the user is in the 'ai' flow (or 'idle' with AI enabled),
 * their messages are forwarded to the AI provider.
 *
 * Escalation: if the AI response has escalate=true, the message
 * is forwarded to the admin chat and the user is notified.
 */
export function renderAIFlowTs(): string {
  return `// Auto-generated by BotForge — do not edit
import { Markup } from 'telegraf'
import type { Context } from 'telegraf'
import { getSession, setFlow, type Session } from '../utils/session'
import { getAIResponse, clearHistory } from '../services/ai.service'

const OWNER_CHAT_ID = process.env.OWNER_CHAT_ID

// ── Handle user message with AI ──────────────────────────────────────────────

export async function handleMessage(ctx: Context & { message: { text: string } }, bot: any): Promise<void> {
  const userId = ctx.from!.id
  const text = ctx.message.text.trim()

  // Typing indicator
  await ctx.sendChatAction('typing')

  const response = await getAIResponse(userId, text)

  // Send AI response
  await ctx.reply(response.text)

  // Handle escalation
  if (response.escalate && OWNER_CHAT_ID) {
    await escalateToHuman(ctx, bot, text, response.text)
  }
}

// ── Reset AI conversation ────────────────────────────────────────────────────

export function resetConversation(userId: number): void {
  clearHistory(userId)
}

// ── Escalation ───────────────────────────────────────────────────────────────

async function escalateToHuman(
  ctx: Context,
  bot: any,
  userMessage: string,
  aiReply: string,
): Promise<void> {
  const from = ctx.from!
  const handle = from.username ? '@' + from.username : 'username yo\\'q'
  const displayName = [from.first_name, from.last_name].filter(Boolean).join(' ')

  const lines = [
    '🔔 Operator kerak!',
    '',
    '👤 ' + displayName + ' (' + handle + ')',
    '🆔 ' + from.id,
    '',
    '💬 Foydalanuvchi: ' + userMessage,
    '🤖 AI javobi: ' + aiReply.slice(0, 200) + (aiReply.length > 200 ? '...' : ''),
    '',
    'AI bu savolga javob bera olmadi.',
  ]

  try {
    await bot.telegram.sendMessage(OWNER_CHAT_ID!, lines.join('\\n'))
    await ctx.reply('Mutaxassis tez orada siz bilan bog\\'lanadi. ⏳')
  } catch (err) {
    console.error('Failed to escalate:', err)
  }
}
`
}
