/**
 * Renders boilerplate files shared by ALL generated bots:
 *   - tsconfig.json
 *   - .gitignore
 *   - .env.example
 *   - README.md
 *
 * These never change per-template — only the template name and env vars vary.
 */

import type { TemplateFile } from '../types'

export function renderTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      module: 'commonjs',
      lib: ['ES2020'],
      outDir: './dist',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      resolveJsonModule: true,
    },
    include: ['src'],
    exclude: ['node_modules', 'dist'],
  }, null, 2)
}

export function renderGitignore(): string {
  return `node_modules/
dist/
.env
*.log
`
}

export function renderEnvExample(envMapping: Record<string, string>): string {
  const lines = [
    '# Required environment variables',
    '# Copy this file to .env and fill in the values',
    '',
  ]
  for (const envVar of Object.keys(envMapping)) {
    lines.push(`${envVar}=`)
  }
  lines.push('')
  return lines.join('\n')
}

export function renderReadme(opts: {
  botName: string
  templateName: string
  envVars: string[]
}): string {
  const envList = opts.envVars.map(v => `- \`${v}\``).join('\n')

  return `# ${opts.botName}

Generated by [BotForge](https://botforge.uz) using the **${opts.templateName}** template.

## Setup

\`\`\`bash
npm install
cp .env.example .env
# Fill in the values in .env
\`\`\`

## Environment variables

${envList}

## Development

\`\`\`bash
npm run dev
\`\`\`

## Production

\`\`\`bash
npm run build
npm start
\`\`\`

## Managed by BotForge

This bot is auto-generated and deployed by BotForge.
Re-generating will overwrite all files. Do not edit manually.
`
}

export function renderPackageJson(opts: {
  name: string
  hasAI: boolean
  aiProvider?: string
}): string {
  const deps: Record<string, string> = {
    dotenv: '^16.4.5',
    telegraf: '^4.16.3',
  }

  if (opts.hasAI) {
    if (opts.aiProvider === 'openai') deps['openai'] = '^4.50.0'
    if (opts.aiProvider === 'gemini') deps['@google/generative-ai'] = '^0.12.0'
  }

  return JSON.stringify({
    name: opts.name,
    version: '1.0.0',
    private: true,
    scripts: {
      build: 'tsc',
      start: 'node dist/bot.js',
      dev: 'ts-node src/bot.ts',
    },
    dependencies: deps,
    devDependencies: {
      '@types/node': '^20.11.5',
      'ts-node': '^10.9.2',
      typescript: '^5.3.3',
    },
  }, null, 2)
}

export function renderBotEntryTs(): string {
  return `import 'dotenv/config'
import { Telegraf } from 'telegraf'
import { handleText, handleContact, handleCallback } from './router'

const BOT_TOKEN = process.env.BOT_TOKEN
if (!BOT_TOKEN) throw new Error('BOT_TOKEN is required')
if (!process.env.OWNER_CHAT_ID) throw new Error('OWNER_CHAT_ID is required')

const bot = new Telegraf(BOT_TOKEN)

bot.start((ctx) => handleText(ctx as any, bot))
bot.on('contact', (ctx) => handleContact(ctx as any, bot))
bot.on('callback_query', (ctx) => handleCallback(ctx as any, bot))
bot.on('text', (ctx) => handleText(ctx as any, bot))

bot.launch({ dropPendingUpdates: true })
  .then(() => console.log('Bot is running'))
  .catch((err) => { console.error('Launch failed:', err); process.exit(1) })

process.once('SIGINT', () => bot.stop('SIGINT'))
process.once('SIGTERM', () => bot.stop('SIGTERM'))
`
}

/**
 * Builds the complete set of boilerplate files.
 * Templates call this + add their own flow files.
 */
export function boilerplateFiles(opts: {
  name: string
  templateName: string
  envMapping: Record<string, string>
  hasAI: boolean
  aiProvider?: string
}): TemplateFile[] {
  const envVars = Object.keys(opts.envMapping)

  return [
    { path: 'package.json', content: renderPackageJson({ name: opts.name, hasAI: opts.hasAI, aiProvider: opts.aiProvider }) },
    { path: 'tsconfig.json', content: renderTsConfig() },
    { path: '.gitignore', content: renderGitignore() },
    { path: '.env.example', content: renderEnvExample(opts.envMapping) },
    { path: 'README.md', content: renderReadme({ botName: opts.name, templateName: opts.templateName, envVars }) },
    { path: 'src/bot.ts', content: renderBotEntryTs() },
  ]
}
