/**
 * Renders src/services/notify.ts for the generated bot.
 *
 * Sends submission summaries to the admin/owner chat.
 * Used by all templates after form completion.
 */
export function renderNotifyTs(botLabel: string): string {
  const labelLiteral = JSON.stringify(botLabel)

  return `// Auto-generated by BotForge — do not edit
import type { Context } from 'telegraf'
import type { Session } from '../utils/session'
import { formatSubmission } from '../utils/session'
import { FIELDS } from '../flows/form.flow'

const OWNER_CHAT_ID = process.env.OWNER_CHAT_ID
const BOT_LABEL = ${labelLiteral}

export async function notifyAdmin(
  bot: { telegram: { sendMessage(chatId: string, text: string): Promise<unknown> } },
  ctx: Context,
  session: Session,
  extra?: string,
): Promise<void> {
  if (!OWNER_CHAT_ID) {
    console.error('OWNER_CHAT_ID is not set')
    return
  }

  const from = ctx.from!
  const handle = from.username ? '@' + from.username : 'username yo\\'q'
  const displayName = [from.first_name, from.last_name].filter(Boolean).join(' ')

  const lines: string[] = [
    BOT_LABEL,
    '',
    'Telegram: ' + displayName + ' (' + handle + ')',
    'ID: ' + from.id,
    '',
    formatSubmission(session, FIELDS),
  ]

  if (extra) {
    lines.push('')
    lines.push(extra)
  }

  try {
    await bot.telegram.sendMessage(OWNER_CHAT_ID, lines.join('\\n'))
  } catch (err) {
    console.error('Failed to notify admin:', err)
  }
}
`
}
