/**
 * Renders src/flows/start.flow.ts for the generated bot.
 *
 * Handles /start: resets session, shows welcome message,
 * then transitions to the appropriate next flow (menu or form).
 */
export function renderStartFlowTs(opts: {
  welcomeMessage: string
  hasMenu: boolean
}): string {
  const welcome = JSON.stringify(opts.welcomeMessage)

  return `// Auto-generated by BotForge — do not edit
import type { Context } from 'telegraf'
import { resetSession, setFlow, type Session } from '../utils/session'
${opts.hasMenu ? "import { show as showMenu } from './menu.flow'" : "import { startForm } from './form.flow'"}

const WELCOME = ${welcome}

export async function handle(ctx: Context, _session: Session, _bot: any): Promise<void> {
  const session = resetSession(ctx.from!.id)
  await ctx.reply(WELCOME)

${opts.hasMenu
    ? `  // Show menu — user picks what to do
  setFlow(session, 'menu')
  await showMenu(ctx, session)`
    : `  // Go straight to form
  setFlow(session, 'form')
  await startForm(ctx)`
}
}
`
}
