import fs from 'fs/promises'
import path from 'path'

interface TemplateFile {
  path: string
  content: string
}

/**
 * Returns the absolute workspace path for a project.
 * Validates the projectId format to prevent path traversal.
 */
export function getWorkspacePath(workspaceBase: string, projectId: string): string {
  // CUIDs are lowercase alphanumeric only — safe for use as directory names.
  if (!/^[a-z0-9]+$/.test(projectId)) {
    throw new Error(`Invalid project ID format: "${projectId}"`)
  }
  const resolved = path.resolve(workspaceBase, projectId)
  // Belt-and-suspenders: ensure result is inside the base directory
  if (!resolved.startsWith(path.resolve(workspaceBase))) {
    throw new Error('Path traversal attempt detected')
  }
  return resolved
}

/** Creates the workspace directory tree. Safe to call if it already exists. */
export async function createWorkspace(workspacePath: string): Promise<void> {
  await fs.mkdir(workspacePath, { recursive: true })
}

/**
 * Removes the workspace directory and all its contents.
 * Called before each deploy so stale source files and the old .env are fully removed
 * rather than partially overwritten. No-op if the directory does not exist.
 */
export async function cleanWorkspace(workspacePath: string): Promise<void> {
  await fs.rm(workspacePath, { recursive: true, force: true })
}

export interface CleanupResult {
  removed: string[]
  errors: string[]
}

/**
 * Removes workspace directories that do not belong to any active project.
 *
 * @param workspaceBase    Root directory containing per-project subdirectories.
 * @param activeProjectIds Set of project IDs whose workspaces should be kept.
 *
 * Only removes directories whose names pass the project-ID format check
 * (lowercase alphanumeric) — extra safety against accidental deletions.
 */
export async function cleanupStaleWorkspaces(
  workspaceBase: string,
  activeProjectIds: Set<string>,
): Promise<CleanupResult> {
  const removed: string[] = []
  const errors: string[] = []

  let entries: import('fs').Dirent[]
  try {
    entries = await fs.readdir(workspaceBase, { withFileTypes: true })
  } catch {
    return { removed, errors } // directory doesn't exist yet — nothing to clean
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    // Only consider directories whose names look like project IDs
    if (!/^[a-z0-9]+$/.test(entry.name)) continue
    if (activeProjectIds.has(entry.name)) continue

    const fullPath = path.join(workspaceBase, entry.name)
    try {
      await fs.rm(fullPath, { recursive: true, force: true })
      removed.push(entry.name)
    } catch (err) {
      errors.push(`${entry.name}: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  return { removed, errors }
}

/**
 * Writes generated source files to the workspace.
 * Creates any nested subdirectories automatically.
 * Only writes files whose paths are relative (no absolute or traversal paths).
 */
export async function writeGeneratedFiles(
  workspacePath: string,
  files: TemplateFile[],
): Promise<void> {
  for (const file of files) {
    // Reject absolute paths or traversal attempts in file paths
    if (path.isAbsolute(file.path) || file.path.includes('..')) {
      throw new Error(`Unsafe file path in snapshot: "${file.path}"`)
    }

    const fullPath = path.join(workspacePath, file.path)
    const dir = path.dirname(fullPath)
    await fs.mkdir(dir, { recursive: true })
    await fs.writeFile(fullPath, file.content, 'utf-8')
  }
}

/**
 * Writes the .env file into the workspace.
 * chmod 600 — readable only by the process owner.
 * Never logs or returns the content.
 */
export async function writeEnvFile(
  workspacePath: string,
  content: string,
): Promise<void> {
  const envPath = path.join(workspacePath, '.env')
  await fs.writeFile(envPath, content, 'utf-8')
  // Restrict to owner read/write only (no group/other access)
  await fs.chmod(envPath, 0o600)
}

/**
 * Builds the .env file content from config data + the template's envMapping.
 *
 * envMapping:  { 'BOT_TOKEN': 'botToken', 'OWNER_CHAT_ID': 'ownerChatId' }
 * configData:  { botToken: '12345:xxx', ownerChatId: '987654321', ... }
 *
 * Output:  "BOT_TOKEN=12345:xxx\nOWNER_CHAT_ID=987654321\n"
 *
 * Values that contain whitespace, #, ", or \ are quoted and escaped.
 * This function is the ONLY place secrets leave the DB and touch the filesystem.
 */
export function buildEnvFileContent(
  configData: Record<string, unknown>,
  envMapping: Record<string, string>,
): string {
  const lines: string[] = ['# Generated by BotForge — do not edit manually', '']

  for (const [envVar, configField] of Object.entries(envMapping)) {
    const raw = configData[configField]
    const value = raw !== undefined && raw !== null ? String(raw) : ''
    lines.push(`${envVar}=${escapeEnvValue(value)}`)
  }

  lines.push('') // trailing newline
  return lines.join('\n')
}

// Wraps values in double quotes and escapes internals only when needed.
function escapeEnvValue(value: string): string {
  if (/[\s#"\\]/.test(value)) {
    return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
  }
  return value
}
